[NetworkSetup] fixed several GSOD, write correctly in inetd.conf for ipv6
Solved GSOD installComplete:
Traceback (most recent call last):
File "/usr/lib/enigma2/python/Components/Console.py", line 37, in finishedCB
File "/usr/lib/enigma2/python/Screens/NetworkSetup.py", line 56, in installComplete
self.session.open(TryQuitMainloop, 2)
File "/usr/lib/enigma2/python/mytest.py", line 333, in open
raise RuntimeError("modal open are allowed only from a screen which is modal!")
RuntimeError: modal open are allowed only from a screen which is modal!
Solved restart inetd.busybox:
Traceback (most recent call last):
File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
File "/usr/lib/enigma2/python/Screens/NetworkSetup.py", line 676, in keyBlue
self.inetdRestart()
File "/usr/lib/enigma2/python/Screens/NetworkSetup.py", line 685, in inetdRestart
Console.ePopen("/etc/init.d/inetd.busybox restart")
TypeError: unbound method ePopen() must be called with Console instance as first argument (got str instance instead)

Now if you write correctly for ipv6 support, before this change the Telnet and FTP services stopped working when support for ipv6 was enabled or disabled