RecordTimer.py: fixe save timers for py3
UnicodeEncodeError: 'ascii' codec can't encode characters in position 206-210: ordinal not in range(128)
[ePyObject] (CallObject(<bound method Session.processDelay of <__main__.Session object at 0xb06ac700>>,()) failed)
**I have to tell you guys, that this has nothing to do with the previous commit, I'm still trying to find the source of these errors that are causing many problems and in many places in E2 since we started working with Python 3, meanwhile trying to find out if There is something wrong with the compilation Platform related to the ascii characters because they are causing many problems.

- this problem arises when trying to save a recording timer in Python 3.

- this problem arises when trying to save a recording timer in Python 3.
- In the hypothetical case that we manage to find the origin of the problem, it is not very difficult to locate these loops to eliminate them.