[MovieList] Prevent crashes when timers fail
In certain corner cases, mostly provoked by AutoTimer, the following
crash could occur:

Error: [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'RecordTimerEntry' object has no attribute 'Filename'
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:246:inContext
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:262:<lambda>
/usr/lib/python2.7/site-packages/twisted/python/context.py:118:callWithContext
/usr/lib/python2.7/site-packages/twisted/python/context.py:81:callWithContext
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:275:JobStart
/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimer.py:587:parseTimer
/usr/lib/enigma2/python/RecordTimer.py:931:timeChanged
/usr/lib/enigma2/python/timer.py:298:timeChanged
/usr/lib/enigma2/python/timer.py:224:addTimerEntry
/usr/lib/enigma2/python/timer.py:263:calcNextActivation
/usr/lib/enigma2/python/timer.py:334:processActivation
/usr/lib/enigma2/python/RecordTimer.py:978:doActivate
/usr/lib/enigma2/python/timer.py:197:stateChanged
/usr/lib/enigma2/python/Components/MovieList.py:371:updateRecordings

This can be caused by a full HDD, which will cause the timer to show as
active, but without having a valid filename.

Deal with this by checking that the timer in question has not failed.