TimerList.py: Apply floor division
Python 3.10

[Screen] Showing screen '['TimerEditList_summary', 'SimpleSummary']'.
[Screen] Showing screen 'TimerEditList'.
[eEPGChannelData] nownext finished(1653721573)
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Co-authored-by: Hains van den Bosch <hainsvdbosch@ziggo.nl>
Co-authored-by: norhap <elfogondesegovia@gmail.com>