message.h: Remove duplicate attribute
The old e2-old_dvbapi patch just moved the attribute 'eSingleLock lock' to another
place in the class body (from line 61 to line 66), and removing of that field
was overlooked when that patch was merged into Enigma2.

In file included from ../../git/lib/gdi/grc.h:20:0,
|                  from ../../git/lib/gui/ewidget.h:4,
|                  from ../../git/lib/actions/action.h:5,
|                  from ../../git/lib/actions/action.cpp:1:
| ../../git/lib/base/message.h:66:14: error: redeclaration of 'eSingleLock eFixedMessagePump<T>::lock'
|   eSingleLock lock;
|               ^~~~
| ../../git/lib/base/message.h:61:14: note: previous declaration 'eSingleLock eFixedMessagePump<T>::lock'
|   eSingleLock lock;
|               ^~~~